/*

	An example of implementating a binary search,
	when searching for a phone, by name

 */

function binarySearch(data, target) {
	//Binary search only works with sorted data
	data
		.sort((a, b) => a.name
			.localeCompare(b.name));

	let start = 0;
	let end = data.length - 1;

	//Define a counter to track how many steps were taken in the search
	let counter = 0;

	while (start <= end) {
		counter++;

		//The key point is to recalculate the middle of the list at each iteration
		let mid = Math.floor((start + end) / 2);

		//String comparison
		if (data[mid].name === target) {
			console.log(data[mid].name)
			return console.log(`

								The user's phone number was found: ${data[mid].phone};
								Position of the searched element in the data list: ${mid};
								Search steps done ${counter}.

								`);
		} else if (data[mid].name < target) {
			start = mid + 1;
		} else {
			end = mid - 1;
		}
	}
	return console.log("Data not found")
}

//Generated by https://www.json-generator.com/
const data = [
	{
		"_id": "5f17351cd351494c8e976b35",
		"age": 22,
		"eyeColor": "green",
		"name": "Nell Hart",
		"gender": "female",
		"company": "ORGANICA",
		"email": "nellhart@organica.com",
		"phone": "+1 (866) 587-3464",
		"address": "326 Irwin Street, Fairlee, Oregon, 5960"
	},
	{
		"_id": "5f17351ce0b305ddd741ece4",
		"age": 30,
		"eyeColor": "green",
		"name": "Angeline Owens",
		"gender": "female",
		"company": "INJOY",
		"email": "angelineowens@injoy.com",
		"phone": "+1 (819) 497-2643",
		"address": "670 Beacon Court, Orviston, New Jersey, 4797"
	},
	{
		"_id": "5f17351ca8bba38065b49184",
		"age": 38,
		"eyeColor": "blue",
		"name": "Ross Christian",
		"gender": "male",
		"company": "DIGIAL",
		"email": "rosschristian@digial.com",
		"phone": "+1 (879) 499-3466",
		"address": "841 Harway Avenue, Wiscon, Federated States Of Micronesia, 6574"
	},
	{
		"_id": "5f17351ce3642c80668e2c42",
		"age": 31,
		"eyeColor": "green",
		"name": "Nola Jacobson",
		"gender": "female",
		"company": "ENTROFLEX",
		"email": "nolajacobson@entroflex.com",
		"phone": "+1 (979) 494-2567",
		"address": "300 Hart Street, Dotsero, Virgin Islands, 4419"
	},
	{
		"_id": "5f17351c1ca4b28bd0708cc9",
		"age": 35,
		"eyeColor": "green",
		"name": "Annabelle Mayo",
		"gender": "female",
		"company": "NEXGENE",
		"email": "annabellemayo@nexgene.com",
		"phone": "+1 (983) 442-3514",
		"address": "444 Monaco Place, Wedgewood, Kansas, 107"
	},
	{
		"_id": "5f17351cf2e1053845449199",
		"age": 25,
		"eyeColor": "brown",
		"name": "Leslie Clark",
		"gender": "female",
		"company": "EXOZENT",
		"email": "leslieclark@exozent.com",
		"phone": "+1 (853) 522-2743",
		"address": "748 Bennet Court, Salix, Virginia, 9447"
	},
	{
		"_id": "5f17351c8802850bd987b20e",
		"age": 37,
		"eyeColor": "green",
		"name": "Harrell Travis",
		"gender": "male",
		"company": "GRAINSPOT",
		"email": "harrelltravis@grainspot.com",
		"phone": "+1 (815) 545-2377",
		"address": "949 Moffat Street, Tetherow, Maine, 7243"
	},
	{
		"_id": "5f17351c2042182c96688d1c",
		"age": 28,
		"eyeColor": "blue",
		"name": "Charity Franks",
		"gender": "female",
		"company": "SEALOUD",
		"email": "charityfranks@sealoud.com",
		"phone": "+1 (829) 549-2240",
		"address": "817 Radde Place, Austinburg, South Dakota, 5021"
	},
	{
		"_id": "5f17351cff0c997f48dbc40f",
		"age": 39,
		"eyeColor": "blue",
		"name": "Mclean Blankenship",
		"gender": "male",
		"company": "INFOTRIPS",
		"email": "mcleanblankenship@infotrips.com",
		"phone": "+1 (822) 412-3765",
		"address": "563 Navy Walk, Waterloo, New Hampshire, 8901"
	},
	{
		"_id": "5f17351cc1ff0cdb82e6bc94",
		"age": 29,
		"eyeColor": "green",
		"name": "Callie Graham",
		"gender": "female",
		"company": "REMOLD",
		"email": "calliegraham@remold.com",
		"phone": "+1 (872) 435-2803",
		"address": "965 Sedgwick Street, Canby, Alaska, 8340"
	},
	{
		"_id": "5f17351cc29a4bb4c41d69a0",
		"age": 34,
		"eyeColor": "green",
		"name": "Marshall Woodward",
		"gender": "male",
		"company": "QUONATA",
		"email": "marshallwoodward@quonata.com",
		"phone": "+1 (943) 533-3479",
		"address": "783 Campus Road, Henrietta, Marshall Islands, 4642"
	},
	{
		"_id": "5f17351c7e857aaa7ea9312c",
		"age": 39,
		"eyeColor": "brown",
		"name": "Cathryn Slater",
		"gender": "female",
		"company": "SYNTAC",
		"email": "cathrynslater@syntac.com",
		"phone": "+1 (855) 566-2331",
		"address": "781 Voorhies Avenue, Sabillasville, Northern Mariana Islands, 4680"
	},
	{
		"_id": "5f17351c2d4b07759dbaf96c",
		"age": 21,
		"eyeColor": "blue",
		"name": "Abby Day",
		"gender": "female",
		"company": "ISOLOGIX",
		"email": "abbyday@isologix.com",
		"phone": "+1 (906) 445-2346",
		"address": "878 Howard Place, Derwood, Connecticut, 851"
	},
	{
		"_id": "5f17351ce1c8c5bd07680368",
		"age": 30,
		"eyeColor": "blue",
		"name": "Torres Benson",
		"gender": "male",
		"company": "DEVILTOE",
		"email": "torresbenson@deviltoe.com",
		"phone": "+1 (928) 415-2141",
		"address": "136 Bryant Street, Jacumba, Rhode Island, 8074"
	},
	{
		"_id": "5f17351cc33e1a18e8cf79ae",
		"age": 30,
		"eyeColor": "green",
		"name": "Carolina Erickson",
		"gender": "female",
		"company": "EXOSIS",
		"email": "carolinaerickson@exosis.com",
		"phone": "+1 (979) 497-3819",
		"address": "810 Cumberland Street, Kipp, Puerto Rico, 5343"
	},
	{
		"_id": "5f17351c46fb0a74ada10c69",
		"age": 31,
		"eyeColor": "green",
		"name": "Hines Franco",
		"gender": "male",
		"company": "ISBOL",
		"email": "hinesfranco@isbol.com",
		"phone": "+1 (986) 415-2675",
		"address": "921 Hendrix Street, Twilight, Washington, 4960"
	},
	{
		"_id": "5f17351cae0fe52531f0b9fb",
		"age": 31,
		"eyeColor": "brown",
		"name": "Nielsen Levy",
		"gender": "male",
		"company": "GEEKMOSIS",
		"email": "nielsenlevy@geekmosis.com",
		"phone": "+1 (827) 518-2609",
		"address": "641 Emerald Street, Englevale, Minnesota, 5599"
	},
	{
		"_id": "5f17351c5149db43971a0323",
		"age": 27,
		"eyeColor": "brown",
		"name": "Miles Macdonald",
		"gender": "male",
		"company": "ASIMILINE",
		"email": "milesmacdonald@asimiline.com",
		"phone": "+1 (855) 525-3952",
		"address": "181 Independence Avenue, Crumpler, Alabama, 9703"
	},
	{
		"_id": "5f17351c5edf2c31eb4bcf65",
		"age": 38,
		"eyeColor": "brown",
		"name": "Britt Spencer",
		"gender": "male",
		"company": "ECRATER",
		"email": "brittspencer@ecrater.com",
		"phone": "+1 (948) 404-3759",
		"address": "443 Greenpoint Avenue, Fedora, New Mexico, 7211"
	},
	{
		"_id": "5f17351c5bc401d07c69d215",
		"age": 22,
		"eyeColor": "green",
		"name": "Berta Guerrero",
		"gender": "female",
		"company": "MIXERS",
		"email": "bertaguerrero@mixers.com",
		"phone": "+1 (970) 597-2214",
		"address": "432 Meserole Street, Cliff, Nevada, 595"
	},
	{
		"_id": "5f17351cb67371f73a5f435a",
		"age": 22,
		"eyeColor": "blue",
		"name": "Dawn Reed",
		"gender": "female",
		"company": "COASH",
		"email": "dawnreed@coash.com",
		"phone": "+1 (848) 420-2598",
		"address": "921 Ryder Street, Lookingglass, Wisconsin, 3059"
	},
	{
		"_id": "5f17351cd9d89e961ce2b1aa",
		"age": 34,
		"eyeColor": "green",
		"name": "Beverly Spears",
		"gender": "female",
		"company": "HOMETOWN",
		"email": "beverlyspears@hometown.com",
		"phone": "+1 (970) 580-2666",
		"address": "405 Wortman Avenue, Katonah, Oklahoma, 2366"
	},
	{
		"_id": "5f17351ce163d5aa184d9ec4",
		"age": 37,
		"eyeColor": "brown",
		"name": "Alvarez Mcdonald",
		"gender": "male",
		"company": "KIGGLE",
		"email": "alvarezmcdonald@kiggle.com",
		"phone": "+1 (842) 542-3837",
		"address": "670 Vernon Avenue, Nicut, Illinois, 4754"
	},
	{
		"_id": "5f17351ced983f6b34caa714",
		"age": 38,
		"eyeColor": "brown",
		"name": "Cathy Colon",
		"gender": "female",
		"company": "MINGA",
		"email": "cathycolon@minga.com",
		"phone": "+1 (865) 404-3182",
		"address": "779 Juliana Place, Boomer, Indiana, 6021"
	},
	{
		"_id": "5f17351c59989aa09409d2e3",
		"age": 23,
		"eyeColor": "brown",
		"name": "Jenny Hodge",
		"gender": "female",
		"company": "GUSHKOOL",
		"email": "jennyhodge@gushkool.com",
		"phone": "+1 (848) 436-2707",
		"address": "401 Kenmore Court, Coultervillle, Nebraska, 2616"
	},
	{
		"_id": "5f17351cc304cf55481804f4",
		"age": 32,
		"eyeColor": "blue",
		"name": "Randolph Cantu",
		"gender": "male",
		"company": "DOGNOSIS",
		"email": "randolphcantu@dognosis.com",
		"phone": "+1 (860) 416-3319",
		"address": "647 Pershing Loop, Hiko, Tennessee, 1531"
	},
	{
		"_id": "5f17351c1174226cb6e348c3",
		"age": 35,
		"eyeColor": "brown",
		"name": "Garner Buck",
		"gender": "male",
		"company": "SENTIA",
		"email": "garnerbuck@sentia.com",
		"phone": "+1 (976) 546-3104",
		"address": "719 Barwell Terrace, Delco, Idaho, 5000"
	},
	{
		"_id": "5f17351c635566d949c58188",
		"age": 29,
		"eyeColor": "blue",
		"name": "Mara Joseph",
		"gender": "female",
		"company": "AUTOMON",
		"email": "marajoseph@automon.com",
		"phone": "+1 (815) 535-3433",
		"address": "148 Pierrepont Street, Dorneyville, Vermont, 6093"
	},
	{
		"_id": "5f17351c3526cbb5fce165a2",
		"age": 20,
		"eyeColor": "green",
		"name": "Katie Lara",
		"gender": "female",
		"company": "MARKETOID",
		"email": "katielara@marketoid.com",
		"phone": "+1 (994) 599-2462",
		"address": "117 Fleet Place, Elizaville, American Samoa, 8790"
	},
	{
		"_id": "5f17351c80b3cd78eff72880",
		"age": 36,
		"eyeColor": "blue",
		"name": "Ray Turner",
		"gender": "male",
		"company": "OATFARM",
		"email": "rayturner@oatfarm.com",
		"phone": "+1 (853) 442-2539",
		"address": "682 Dupont Street, Finderne, North Carolina, 2809"
	},
	{
		"_id": "5f17351c8ed6f9ac34098da8",
		"age": 26,
		"eyeColor": "green",
		"name": "Mccarthy Wall",
		"gender": "male",
		"company": "ENDIPINE",
		"email": "mccarthywall@endipine.com",
		"phone": "+1 (947) 600-2974",
		"address": "833 Banner Avenue, Strong, Ohio, 2822"
	},
	{
		"_id": "5f17351ca5158f620524455a",
		"age": 37,
		"eyeColor": "green",
		"name": "Ballard Rodgers",
		"gender": "male",
		"company": "SLAX",
		"email": "ballardrodgers@slax.com",
		"phone": "+1 (985) 410-3137",
		"address": "987 Tehama Street, Tyhee, Hawaii, 862"
	},
	{
		"_id": "5f17351cbc08c764e586ecea",
		"age": 25,
		"eyeColor": "brown",
		"name": "Annie Foster",
		"gender": "female",
		"company": "PETICULAR",
		"email": "anniefoster@peticular.com",
		"phone": "+1 (996) 509-3978",
		"address": "392 Elizabeth Place, Dexter, Guam, 8362"
	},
	{
		"_id": "5f17351cdd2f952c7cb36466",
		"age": 40,
		"eyeColor": "green",
		"name": "Pittman Simpson",
		"gender": "male",
		"company": "ENJOLA",
		"email": "pittmansimpson@enjola.com",
		"phone": "+1 (886) 422-3130",
		"address": "884 Clymer Street, Glasgow, Georgia, 7105"
	},
	{
		"_id": "5f17351c24c6f676f078309b",
		"age": 35,
		"eyeColor": "blue",
		"name": "Burke Crosby",
		"gender": "male",
		"company": "POSHOME",
		"email": "burkecrosby@poshome.com",
		"phone": "+1 (827) 599-2512",
		"address": "448 Freeman Street, Chumuckla, Utah, 562"
	},
	{
		"_id": "5f17351cdffde0e3c66a4258",
		"age": 34,
		"eyeColor": "brown",
		"name": "Hunter Cervantes",
		"gender": "male",
		"company": "TOYLETRY",
		"email": "huntercervantes@toyletry.com",
		"phone": "+1 (957) 416-2889",
		"address": "158 Gold Street, Healy, Massachusetts, 416"
	},
	{
		"_id": "5f17351cc227ef18e0192a18",
		"age": 40,
		"eyeColor": "brown",
		"name": "Perry Boone",
		"gender": "male",
		"company": "TERRAGO",
		"email": "perryboone@terrago.com",
		"phone": "+1 (802) 523-3615",
		"address": "184 Glen Street, Wells, Montana, 3459"
	},
	{
		"_id": "5f17351ce44611d24c9e1399",
		"age": 23,
		"eyeColor": "blue",
		"name": "Corinne Kelley",
		"gender": "female",
		"company": "GALLAXIA",
		"email": "corinnekelley@gallaxia.com",
		"phone": "+1 (818) 558-3852",
		"address": "138 Rutledge Street, Maplewood, Colorado, 4071"
	},
	{
		"_id": "5f17351cce32dcb798019ee1",
		"age": 40,
		"eyeColor": "brown",
		"name": "Maxwell Frazier",
		"gender": "male",
		"company": "DIGINETIC",
		"email": "maxwellfrazier@diginetic.com",
		"phone": "+1 (901) 545-3688",
		"address": "370 Franklin Street, Rodman, North Dakota, 8739"
	},
	{
		"_id": "5f17351c73f77551657a9fbe",
		"age": 33,
		"eyeColor": "brown",
		"name": "Valdez Bright",
		"gender": "male",
		"company": "ZORROMOP",
		"email": "valdezbright@zorromop.com",
		"phone": "+1 (969) 406-2348",
		"address": "790 Drew Street, Homestead, Wyoming, 7114"
	},
	{
		"_id": "5f17351cb12c53ec6b6e7f1c",
		"age": 21,
		"eyeColor": "green",
		"name": "Stone Wolf",
		"gender": "male",
		"company": "XIIX",
		"email": "stonewolf@xiix.com",
		"phone": "+1 (955) 554-3695",
		"address": "480 Caton Place, Thornport, Palau, 5652"
	},
	{
		"_id": "5f17351ce4f14375bbb9154a",
		"age": 34,
		"eyeColor": "brown",
		"name": "Burns Holland",
		"gender": "male",
		"company": "WATERBABY",
		"email": "burnsholland@waterbaby.com",
		"phone": "+1 (805) 479-3102",
		"address": "541 Prospect Place, Sehili, Missouri, 3096"
	},
	{
		"_id": "5f17351cab97bc4357a43796",
		"age": 34,
		"eyeColor": "green",
		"name": "Morgan Mcguire",
		"gender": "male",
		"company": "NAMEBOX",
		"email": "morganmcguire@namebox.com",
		"phone": "+1 (963) 404-3920",
		"address": "493 Decatur Street, Herald, Arkansas, 1123"
	},
	{
		"_id": "5f17351c971dfefc84acaa46",
		"age": 20,
		"eyeColor": "blue",
		"name": "Doreen Conway",
		"gender": "female",
		"company": "INQUALA",
		"email": "doreenconway@inquala.com",
		"phone": "+1 (893) 560-3606",
		"address": "688 Polar Street, Roeville, Louisiana, 5362"
	},
	{
		"_id": "5f17351c5bd69b747f017381",
		"age": 37,
		"eyeColor": "green",
		"name": "Stuart Sanchez",
		"gender": "male",
		"company": "DANCITY",
		"email": "stuartsanchez@dancity.com",
		"phone": "+1 (922) 597-2072",
		"address": "397 College Place, Bend, Mississippi, 513"
	},
	{
		"_id": "5f17351cdfe7e7fea0b2646c",
		"age": 37,
		"eyeColor": "blue",
		"name": "Sheppard Ford",
		"gender": "male",
		"company": "PATHWAYS",
		"email": "sheppardford@pathways.com",
		"phone": "+1 (931) 414-2697",
		"address": "285 Oxford Walk, Sisquoc, Texas, 9513"
	},
	{
		"_id": "5f17351c5ecc4ca7cf8b720c",
		"age": 25,
		"eyeColor": "green",
		"name": "Hannah Meyers",
		"gender": "female",
		"company": "EQUICOM",
		"email": "hannahmeyers@equicom.com",
		"phone": "+1 (822) 472-2857",
		"address": "291 Dekoven Court, Maury, Iowa, 3649"
	},
	{
		"_id": "5f17351c2e8af68d67aa90ed",
		"age": 33,
		"eyeColor": "green",
		"name": "Patti Gutierrez",
		"gender": "female",
		"company": "HAWKSTER",
		"email": "pattigutierrez@hawkster.com",
		"phone": "+1 (957) 482-3033",
		"address": "448 Bushwick Avenue, Durham, West Virginia, 474"
	},
	{
		"_id": "5f17351c622326d384325668",
		"age": 22,
		"eyeColor": "blue",
		"name": "Pitts Hensley",
		"gender": "male",
		"company": "HAIRPORT",
		"email": "pittshensley@hairport.com",
		"phone": "+1 (980) 502-3640",
		"address": "866 Farragut Road, Layhill, California, 5625"
	},
	{
		"_id": "5f17351c5b874abe43c18838",
		"age": 34,
		"eyeColor": "green",
		"name": "Wilcox Farley",
		"gender": "male",
		"company": "RECOGNIA",
		"email": "wilcoxfarley@recognia.com",
		"phone": "+1 (831) 546-2000",
		"address": "867 Court Square, Greenwich, District Of Columbia, 2009"
	},
	{
		"_id": "5f17351cb8210a80ed4afb9e",
		"age": 34,
		"eyeColor": "brown",
		"name": "Stevenson Dyer",
		"gender": "male",
		"company": "PLASMOS",
		"email": "stevensondyer@plasmos.com",
		"phone": "+1 (816) 560-2641",
		"address": "278 Emerson Place, Navarre, Delaware, 6251"
	},
	{
		"_id": "5f17351c4298d43db414f0a3",
		"age": 40,
		"eyeColor": "brown",
		"name": "Justice Wise",
		"gender": "male",
		"company": "PHORMULA",
		"email": "justicewise@phormula.com",
		"phone": "+1 (818) 562-3976",
		"address": "662 Lake Avenue, Crawfordsville, Kentucky, 5547"
	},
	{
		"_id": "5f17351c333b77866b7f11e8",
		"age": 20,
		"eyeColor": "green",
		"name": "Romero Stewart",
		"gender": "male",
		"company": "JOVIOLD",
		"email": "romerostewart@joviold.com",
		"phone": "+1 (828) 435-2146",
		"address": "598 Merit Court, Kennedyville, Pennsylvania, 2018"
	},
	{
		"_id": "5f17351c7e178e198e3679e8",
		"age": 38,
		"eyeColor": "green",
		"name": "Knight Stephenson",
		"gender": "male",
		"company": "SUPPORTAL",
		"email": "knightstephenson@supportal.com",
		"phone": "+1 (991) 521-2956",
		"address": "334 Stratford Road, Kersey, New York, 9199"
	},
	{
		"_id": "5f17351c8dc16efb51a2de69",
		"age": 37,
		"eyeColor": "blue",
		"name": "Dee Perez",
		"gender": "female",
		"company": "MANTRIX",
		"email": "deeperez@mantrix.com",
		"phone": "+1 (907) 598-2395",
		"address": "756 Atkins Avenue, Rivera, South Carolina, 7859"
	},
	{
		"_id": "5f17351ca9c1330e96e725c2",
		"age": 33,
		"eyeColor": "green",
		"name": "Josie Mclaughlin",
		"gender": "female",
		"company": "SPORTAN",
		"email": "josiemclaughlin@sportan.com",
		"phone": "+1 (952) 440-2257",
		"address": "959 Bridge Street, Rodanthe, Florida, 6918"
	},
	{
		"_id": "5f17351c097db8c331e6b01c",
		"age": 23,
		"eyeColor": "green",
		"name": "Noemi Velazquez",
		"gender": "female",
		"company": "QABOOS",
		"email": "noemivelazquez@qaboos.com",
		"phone": "+1 (866) 447-3452",
		"address": "682 Elliott Walk, Blue, Maryland, 4249"
	},
	{
		"_id": "5f17351c3dbd0da16f2aa847",
		"age": 36,
		"eyeColor": "brown",
		"name": "Tami Hopper",
		"gender": "female",
		"company": "UTARIAN",
		"email": "tamihopper@utarian.com",
		"phone": "+1 (815) 407-2477",
		"address": "580 Saratoga Avenue, Turah, Arizona, 6003"
	},
	{
		"_id": "5f17351c39efecf0d3bd7ee1",
		"age": 22,
		"eyeColor": "brown",
		"name": "Casandra Curry",
		"gender": "female",
		"company": "ACUSAGE",
		"email": "casandracurry@acusage.com",
		"phone": "+1 (904) 579-3159",
		"address": "346 Conover Street, Brogan, Oregon, 3835"
	},
	{
		"_id": "5f17351c73ddc05c16b17f0f",
		"age": 26,
		"eyeColor": "blue",
		"name": "Gracie Chavez",
		"gender": "female",
		"company": "DEEPENDS",
		"email": "graciechavez@deepends.com",
		"phone": "+1 (842) 490-2286",
		"address": "513 Newton Street, Ferney, New Jersey, 809"
	},
	{
		"_id": "5f17351c1347b2cf74b25339",
		"age": 28,
		"eyeColor": "brown",
		"name": "Maritza Castaneda",
		"gender": "female",
		"company": "ZORK",
		"email": "maritzacastaneda@zork.com",
		"phone": "+1 (846) 428-2768",
		"address": "410 Rutherford Place, Snyderville, Federated States Of Micronesia, 9312"
	},
	{
		"_id": "5f17351c857790c7d5c6240d",
		"age": 20,
		"eyeColor": "green",
		"name": "Emily Callahan",
		"gender": "female",
		"company": "OPTICON",
		"email": "emilycallahan@opticon.com",
		"phone": "+1 (939) 494-2525",
		"address": "666 Monroe Place, Reno, Virgin Islands, 4343"
	},
	{
		"_id": "5f17351c0ab22c308d48f026",
		"age": 34,
		"eyeColor": "green",
		"name": "Mallory Fletcher",
		"gender": "female",
		"company": "FIREWAX",
		"email": "malloryfletcher@firewax.com",
		"phone": "+1 (900) 535-2436",
		"address": "386 Engert Avenue, Riverton, Kansas, 2907"
	},
	{
		"_id": "5f17351c77c72b8b957417dd",
		"age": 31,
		"eyeColor": "green",
		"name": "Mann Tate",
		"gender": "male",
		"company": "EYEWAX",
		"email": "manntate@eyewax.com",
		"phone": "+1 (944) 532-2493",
		"address": "539 Flatlands Avenue, Williamson, Virginia, 1030"
	},
	{
		"_id": "5f17351c3a60b47d3d4bb129",
		"age": 39,
		"eyeColor": "brown",
		"name": "Wall Franklin",
		"gender": "male",
		"company": "KRAGGLE",
		"email": "wallfranklin@kraggle.com",
		"phone": "+1 (948) 447-3641",
		"address": "114 Hewes Street, Wolcott, Maine, 5749"
	},
	{
		"_id": "5f17351c30852170742cd375",
		"age": 29,
		"eyeColor": "green",
		"name": "Terry Harper",
		"gender": "male",
		"company": "AUSTECH",
		"email": "terryharper@austech.com",
		"phone": "+1 (852) 481-2272",
		"address": "753 Hicks Street, Rosburg, South Dakota, 9082"
	},
	{
		"_id": "5f17351c08a615d137e2257f",
		"age": 21,
		"eyeColor": "brown",
		"name": "Galloway Davis",
		"gender": "male",
		"company": "CEMENTION",
		"email": "gallowaydavis@cemention.com",
		"phone": "+1 (959) 532-3319",
		"address": "388 Fairview Place, Grapeview, New Hampshire, 4721"
	},
	{
		"_id": "5f17351c64fa44695479dd97",
		"age": 27,
		"eyeColor": "blue",
		"name": "Maynard Frank",
		"gender": "male",
		"company": "WAZZU",
		"email": "maynardfrank@wazzu.com",
		"phone": "+1 (894) 519-3481",
		"address": "429 Vanderbilt Avenue, Cleary, Alaska, 4050"
	},
	{
		"_id": "5f17351ce7c0f65d5c23b990",
		"age": 25,
		"eyeColor": "blue",
		"name": "Jeanine Martinez",
		"gender": "female",
		"company": "FIBRODYNE",
		"email": "jeaninemartinez@fibrodyne.com",
		"phone": "+1 (996) 452-2299",
		"address": "159 Alton Place, Marysville, Marshall Islands, 6521"
	},
	{
		"_id": "5f17351c0c2cf7c1bb0ef122",
		"age": 39,
		"eyeColor": "green",
		"name": "Jimenez Watson",
		"gender": "male",
		"company": "STRALUM",
		"email": "jimenezwatson@stralum.com",
		"phone": "+1 (871) 583-2500",
		"address": "853 Gelston Avenue, Grantville, Northern Mariana Islands, 9716"
	},
	{
		"_id": "5f17351ccedb419b7f7b0ec5",
		"age": 26,
		"eyeColor": "brown",
		"name": "Rutledge James",
		"gender": "male",
		"company": "BUNGA",
		"email": "rutledgejames@bunga.com",
		"phone": "+1 (969) 423-3142",
		"address": "405 Classon Avenue, Jacksonwald, Connecticut, 8601"
	},
	{
		"_id": "5f17351c513301acd986221b",
		"age": 31,
		"eyeColor": "brown",
		"name": "Boyd Rodriquez",
		"gender": "male",
		"company": "ASSITIA",
		"email": "boydrodriquez@assitia.com",
		"phone": "+1 (812) 573-3726",
		"address": "327 Ferris Street, Yukon, Rhode Island, 8963"
	},
	{
		"_id": "5f17351c83aa38458102df1f",
		"age": 25,
		"eyeColor": "blue",
		"name": "Olga Howell",
		"gender": "female",
		"company": "NETILITY",
		"email": "olgahowell@netility.com",
		"phone": "+1 (889) 514-2632",
		"address": "364 Madison Place, Swartzville, Puerto Rico, 3017"
	},
	{
		"_id": "5f17351cbbe0129d12918248",
		"age": 39,
		"eyeColor": "brown",
		"name": "Deena Knowles",
		"gender": "female",
		"company": "MARQET",
		"email": "deenaknowles@marqet.com",
		"phone": "+1 (961) 414-3443",
		"address": "627 Foster Avenue, Wanship, Washington, 4914"
	},
	{
		"_id": "5f17351c62f9a30330bb750c",
		"age": 21,
		"eyeColor": "brown",
		"name": "Reyes Byrd",
		"gender": "male",
		"company": "LUNCHPAD",
		"email": "reyesbyrd@lunchpad.com",
		"phone": "+1 (870) 558-3962",
		"address": "791 Meeker Avenue, Choctaw, Minnesota, 9178"
	},
	{
		"_id": "5f17351c9c4803c63ecbdff6",
		"age": 34,
		"eyeColor": "green",
		"name": "Terry Dickson",
		"gender": "female",
		"company": "PYRAMIS",
		"email": "terrydickson@pyramis.com",
		"phone": "+1 (975) 450-3612",
		"address": "472 Hampton Avenue, Roosevelt, Alabama, 1081"
	},
	{
		"_id": "5f17351c936153d0045513d8",
		"age": 31,
		"eyeColor": "brown",
		"name": "Long Obrien",
		"gender": "male",
		"company": "PYRAMI",
		"email": "longobrien@pyrami.com",
		"phone": "+1 (980) 413-2215",
		"address": "334 Fillmore Place, Blende, New Mexico, 4888"
	},
	{
		"_id": "5f17351c53353c3a29193a3b",
		"age": 26,
		"eyeColor": "brown",
		"name": "Beulah Nelson",
		"gender": "female",
		"company": "ISOLOGIA",
		"email": "beulahnelson@isologia.com",
		"phone": "+1 (990) 530-2080",
		"address": "474 Delmonico Place, Interlochen, Nevada, 2665"
	},
	{
		"_id": "5f17351c74350e3308f40592",
		"age": 24,
		"eyeColor": "brown",
		"name": "Berry Stevenson",
		"gender": "male",
		"company": "SPLINX",
		"email": "berrystevenson@splinx.com",
		"phone": "+1 (830) 459-3761",
		"address": "351 McKinley Avenue, Taft, Wisconsin, 2202"
	},
	{
		"_id": "5f17351c32e60c33d7c8f854",
		"age": 20,
		"eyeColor": "green",
		"name": "Solis Sharp",
		"gender": "male",
		"company": "INTERGEEK",
		"email": "solissharp@intergeek.com",
		"phone": "+1 (968) 524-3550",
		"address": "128 Johnson Avenue, Reinerton, Oklahoma, 7505"
	},
	{
		"_id": "5f17351cd20e1bdb7590091a",
		"age": 27,
		"eyeColor": "brown",
		"name": "Eunice Gilliam",
		"gender": "female",
		"company": "SONGBIRD",
		"email": "eunicegilliam@songbird.com",
		"phone": "+1 (811) 560-3833",
		"address": "265 Chestnut Street, Ladera, Illinois, 7011"
	},
	{
		"_id": "5f17351c4beb3d1f64bb0c9c",
		"age": 31,
		"eyeColor": "blue",
		"name": "Powell Galloway",
		"gender": "male",
		"company": "AQUOAVO",
		"email": "powellgalloway@aquoavo.com",
		"phone": "+1 (901) 527-2431",
		"address": "860 Poly Place, Garnet, Indiana, 1798"
	},
	{
		"_id": "5f17351ccb9b1585dfeb3a43",
		"age": 21,
		"eyeColor": "brown",
		"name": "Mejia Wheeler",
		"gender": "male",
		"company": "CENTURIA",
		"email": "mejiawheeler@centuria.com",
		"phone": "+1 (992) 426-3587",
		"address": "665 Poplar Street, Craig, Nebraska, 2823"
	},
	{
		"_id": "5f17351cd3b27b527e7bf995",
		"age": 29,
		"eyeColor": "green",
		"name": "Fernandez Hopkins",
		"gender": "male",
		"company": "ZOARERE",
		"email": "fernandezhopkins@zoarere.com",
		"phone": "+1 (920) 410-2008",
		"address": "705 Duffield Street, Westboro, Tennessee, 3929"
	},
	{
		"_id": "5f17351cdeec9104d96ea566",
		"age": 37,
		"eyeColor": "brown",
		"name": "Wendi Rios",
		"gender": "female",
		"company": "REMOTION",
		"email": "wendirios@remotion.com",
		"phone": "+1 (964) 505-3149",
		"address": "523 Powers Street, Camas, Idaho, 4014"
	},
	{
		"_id": "5f17351ce356e67c9d4c1689",
		"age": 22,
		"eyeColor": "brown",
		"name": "Dillard Ramos",
		"gender": "male",
		"company": "HELIXO",
		"email": "dillardramos@helixo.com",
		"phone": "+1 (814) 554-3361",
		"address": "673 Lewis Place, Riegelwood, Vermont, 4537"
	},
	{
		"_id": "5f17351c0682181064e49d89",
		"age": 28,
		"eyeColor": "blue",
		"name": "Merrill Mays",
		"gender": "male",
		"company": "EWAVES",
		"email": "merrillmays@ewaves.com",
		"phone": "+1 (936) 574-3669",
		"address": "109 Vanderveer Street, Beyerville, American Samoa, 8630"
	},
	{
		"_id": "5f17351c8f0b6d6b4faf8976",
		"age": 26,
		"eyeColor": "blue",
		"name": "Foster Bishop",
		"gender": "male",
		"company": "VENDBLEND",
		"email": "fosterbishop@vendblend.com",
		"phone": "+1 (900) 513-2786",
		"address": "739 Gotham Avenue, Hondah, North Carolina, 3775"
	},
	{
		"_id": "5f17351cbed3ae305d9e5dc8",
		"age": 24,
		"eyeColor": "blue",
		"name": "Morse Henderson",
		"gender": "male",
		"company": "ANDERSHUN",
		"email": "morsehenderson@andershun.com",
		"phone": "+1 (994) 520-3506",
		"address": "145 Will Place, Stewart, Ohio, 7845"
	},
	{
		"_id": "5f17351cc63d897e6e317fe9",
		"age": 35,
		"eyeColor": "blue",
		"name": "Amalia Chaney",
		"gender": "female",
		"company": "EVENTEX",
		"email": "amaliachaney@eventex.com",
		"phone": "+1 (954) 532-2244",
		"address": "152 Arlington Avenue, Cade, Hawaii, 422"
	},
	{
		"_id": "5f17351c9301f95c8241340a",
		"age": 34,
		"eyeColor": "blue",
		"name": "Marquez Wilder",
		"gender": "male",
		"company": "UNQ",
		"email": "marquezwilder@unq.com",
		"phone": "+1 (999) 585-3763",
		"address": "336 Arion Place, Loyalhanna, Guam, 6812"
	},
	{
		"_id": "5f17351ca6a54df1cbb1725e",
		"age": 30,
		"eyeColor": "brown",
		"name": "Brandi Stephens",
		"gender": "female",
		"company": "BYTREX",
		"email": "brandistephens@bytrex.com",
		"phone": "+1 (900) 526-3758",
		"address": "156 McClancy Place, Westphalia, Georgia, 3765"
	},
	{
		"_id": "5f17351c33eb83029a1c2fe3",
		"age": 35,
		"eyeColor": "brown",
		"name": "Meadows Ramirez",
		"gender": "male",
		"company": "SLOFAST",
		"email": "meadowsramirez@slofast.com",
		"phone": "+1 (968) 474-2958",
		"address": "768 Newel Street, Allensworth, Utah, 8109"
	},
	{
		"_id": "5f17351c1d9f73f431c88fa3",
		"age": 39,
		"eyeColor": "brown",
		"name": "Spears Flores",
		"gender": "male",
		"company": "FREAKIN",
		"email": "spearsflores@freakin.com",
		"phone": "+1 (962) 426-3018",
		"address": "805 Dennett Place, Gordon, Massachusetts, 7043"
	},
	{
		"_id": "5f17351cf07636d0cf55c19e",
		"age": 23,
		"eyeColor": "green",
		"name": "Diaz Clemons",
		"gender": "male",
		"company": "DUFLEX",
		"email": "diazclemons@duflex.com",
		"phone": "+1 (987) 481-3591",
		"address": "350 Portland Avenue, Brady, Montana, 692"
	},
	{
		"_id": "5f17351c4ca9f0f90206c468",
		"age": 23,
		"eyeColor": "blue",
		"name": "Murphy Atkinson",
		"gender": "male",
		"company": "NETPLODE",
		"email": "murphyatkinson@netplode.com",
		"phone": "+1 (912) 449-3285",
		"address": "858 Kings Place, Topanga, Colorado, 2786"
	},
	{
		"_id": "5f17351c88b06b941687fce7",
		"age": 25,
		"eyeColor": "green",
		"name": "Letitia Prince",
		"gender": "female",
		"company": "ENQUILITY",
		"email": "letitiaprince@enquility.com",
		"phone": "+1 (853) 515-3587",
		"address": "632 Frost Street, Darlington, North Dakota, 870"
	},
	{
		"_id": "5f17351cf340dfec4c76ca45",
		"age": 33,
		"eyeColor": "blue",
		"name": "Bentley Carpenter",
		"gender": "male",
		"company": "AUSTEX",
		"email": "bentleycarpenter@austex.com",
		"phone": "+1 (853) 497-2632",
		"address": "600 Rockaway Parkway, Gerton, Wyoming, 8743"
	},
	{
		"_id": "5f17351c70fbaad4192102b7",
		"age": 25,
		"eyeColor": "brown",
		"name": "Jaime Joyner",
		"gender": "female",
		"company": "SONIQUE",
		"email": "jaimejoyner@sonique.com",
		"phone": "+1 (942) 544-2754",
		"address": "423 Summit Street, Onton, Palau, 5594"
	},
	{
		"_id": "5f17351c6a1aac74a572337d",
		"age": 31,
		"eyeColor": "blue",
		"name": "Janis Farmer",
		"gender": "female",
		"company": "AQUACINE",
		"email": "janisfarmer@aquacine.com",
		"phone": "+1 (815) 502-3016",
		"address": "945 Neptune Avenue, Clara, Missouri, 5995"
	}
]

binarySearch(data, "Casandra Curry");

/*

	Details about the binary search algorithm in Grokking Algorithms:
	An Illustrated Guide for Programmers and Other Curious People by Aditya Bhargava (2016).

 */
